/* Hack to fix up incorrect C prototypes generated by MIDL for COM methods returning
 * aggregates */
#define INITGUID
#include <guiddef.h>

#include "d3d12.h"
#undef ID3D12Resource_GetDesc

static inline D3D12_RESOURCE_DESC ID3D12Resource_GetDesc(ID3D12Resource *iface)
{
	D3D12_RESOURCE_DESC ret;
	D3D12_RESOURCE_DESC *(WINAPI * p_GetDesc)(ID3D12Resource *iface, D3D12_RESOURCE_DESC *desc);
	p_GetDesc = (void *)iface->lpVtbl->GetDesc;
	p_GetDesc(iface, &ret);
	return ret;
}
